# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(886, 364)
        MainWindow.setStyleSheet("color: rgb(85, 87, 83);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(350, 240, 160, 80))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.speechtotext = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.speechtotext.setStyleSheet("font: 63 italic 12pt \"Inter\";")
        self.speechtotext.setObjectName("speechtotext")
        self.verticalLayout_2.addWidget(self.speechtotext)
        self.texttospeech = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.texttospeech.setStyleSheet("font: 63 italic 12pt \"Inter\";")
        self.texttospeech.setObjectName("texttospeech")
        self.verticalLayout_2.addWidget(self.texttospeech)
        self.email = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.email.setStyleSheet("font: 63 italic 12pt \"Inter\";")
        self.email.setObjectName("email")
        self.verticalLayout_2.addWidget(self.email)
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(620, 240, 171, 31))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.outLan = QtWidgets.QComboBox(self.verticalLayoutWidget_3)
        self.outLan.setStyleSheet("font: 63 italic 12pt \"Inter\";")
        self.outLan.setObjectName("outLan")
        self.verticalLayout_3.addWidget(self.outLan)
        self.input_text = QtWidgets.QTextEdit(self.centralwidget)
        self.input_text.setGeometry(QtCore.QRect(10, 40, 391, 191))
        self.input_text.setStyleSheet("font: 63 italic 12pt \"Inter\";")
        self.input_text.setObjectName("input_text")
        self.translat_button = QtWidgets.QPushButton(self.centralwidget)
        self.translat_button.setGeometry(QtCore.QRect(410, 110, 80, 18))
        self.translat_button.setStyleSheet("font: 63 italic 12pt \"Inter\";")
        self.translat_button.setObjectName("translat_button")
        self.output_text = QtWidgets.QTextEdit(self.centralwidget)
        self.output_text.setGeometry(QtCore.QRect(510, 30, 361, 91))
        self.output_text.setStyleSheet("font: 63 italic 12pt \"Inter\";")
        self.output_text.setObjectName("output_text")
        self.output_text_2 = QtWidgets.QTextEdit(self.centralwidget)
        self.output_text_2.setGeometry(QtCore.QRect(510, 150, 361, 91))
        self.output_text_2.setObjectName("output_text_2")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 10, 211, 31))
        self.label.setStyleSheet("font: 63 italic 16pt \"Inter\";")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(520, 0, 211, 31))
        self.label_2.setStyleSheet("font: 63 italic 14pt \"Inter\";")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(520, 120, 211, 31))
        self.label_3.setStyleSheet("font: 63 italic 14pt \"Inter\";")
        self.label_3.setObjectName("label_3")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 886, 17))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.speechtotext.setText(_translate("MainWindow", "Speech to Text"))
        self.texttospeech.setText(_translate("MainWindow", "Text to Speech"))
        self.email.setText(_translate("MainWindow", "Send to Email"))
        self.translat_button.setText(_translate("MainWindow", "Translate"))
        self.label.setText(_translate("MainWindow", "Input for translate"))
        self.label_2.setText(_translate("MainWindow", "Output of Translate"))
        self.label_3.setText(_translate("MainWindow", "Pronunciation of Output"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
