# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(886, 355)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 871, 211))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.input_text = QtWidgets.QTextEdit(self.horizontalLayoutWidget)
        self.input_text.setObjectName("input_text")
        self.horizontalLayout.addWidget(self.input_text)
        self.translat_button = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.translat_button.setObjectName("translat_button")
        self.horizontalLayout.addWidget(self.translat_button)
        self.output_text = QtWidgets.QTextEdit(self.horizontalLayoutWidget)
        self.output_text.setObjectName("output_text")
        self.horizontalLayout.addWidget(self.output_text)
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(360, 220, 160, 80))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.speechtotext = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.speechtotext.setObjectName("speechtotext")
        self.verticalLayout_2.addWidget(self.speechtotext)
        self.texttospeech = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.texttospeech.setObjectName("texttospeech")
        self.verticalLayout_2.addWidget(self.texttospeech)
        self.email = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.email.setObjectName("email")
        self.verticalLayout_2.addWidget(self.email)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(90, 220, 160, 31))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.inLan = QtWidgets.QComboBox(self.verticalLayoutWidget_2)
        self.inLan.setObjectName("inLan")
        self.inLan.addItem("")
        self.inLan.addItem("")
        self.inLan.addItem("")
        self.inLan.addItem("")
        self.inLan.addItem("")
        self.verticalLayout.addWidget(self.inLan)
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(630, 220, 160, 31))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.outLan = QtWidgets.QComboBox(self.verticalLayoutWidget_3)
        self.outLan.setObjectName("outLan")
        self.outLan.addItem("")
        self.outLan.addItem("")
        self.outLan.addItem("")
        self.outLan.addItem("")
        self.outLan.addItem("")
        self.verticalLayout_3.addWidget(self.outLan)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 886, 17))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.translat_button.setText(_translate("MainWindow", "Translate"))
        self.speechtotext.setText(_translate("MainWindow", "Speech to Text"))
        self.texttospeech.setText(_translate("MainWindow", "Text to Speech"))
        self.email.setText(_translate("MainWindow", "Send to Email"))
        self.inLan.setItemText(0, _translate("MainWindow", "English"))
        self.inLan.setItemText(1, _translate("MainWindow", "Gujarat"))
        self.inLan.setItemText(2, _translate("MainWindow", "Hindi"))
        self.inLan.setItemText(3, _translate("MainWindow", "German"))
        self.inLan.setItemText(4, _translate("MainWindow", "Spanish"))
        self.outLan.setItemText(0, _translate("MainWindow", "English"))
        self.outLan.setItemText(1, _translate("MainWindow", "Gujarat"))
        self.outLan.setItemText(2, _translate("MainWindow", "Hindi"))
        self.outLan.setItemText(3, _translate("MainWindow", "German"))
        self.outLan.setItemText(4, _translate("MainWindow", "Spanish"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
